name: pggtyper
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
  - r
dependencies:
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_6
  - blas=1.0=mkl
  - boost=1.67.0=py37_4
  - bzip2=1.0.6=h14c3975_1002
  - ca-certificates=2019.5.15=1
  - certifi=2019.6.16=py37_1
  - cmake=3.14.0=h52cb24c_0
  - curl=7.64.1=hf8cf82a_0
  - expat=2.2.6=he6710b0_0
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_6
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_6
  - icu=58.2=h211956c_0
  - intel-openmp=2019.4=243
  - jellyfish=2.2.10=h6bb024c_1
  - jemalloc=4.5.0=0
  - krb5=1.16.3=h05b26f9_1001
  - libboost=1.67.0=h46d08c1_4
  - libcurl=7.64.1=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=h4deb6c0_3
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libuv=1.28.0=h516909a_0
  - mkl=2019.4=243
  - mkl-service=2.0.2=py37h7b6447c_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.0.2=py37hd81dba3_0
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.16.4=py37h7e9f1db_0
  - numpy-base=1.16.4=py37hde5b4d6_0
  - openssl=1.1.1=h7b6447c_0
  - pip=19.2.2=py37_0
  - py-boost=1.67.0=py37h04863e7_4
  - python=3.7.3=h33d41f4_1
  - readline=8.0=hf8c457e_0
  - rhash=1.3.8=h1ba5d50_0
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.29.0=hcee41ef_1
  - tk=8.6.9=h84994c4_1001
  - wheel=0.33.4=py37_0
  - xz=5.2.4=h14c3975_1001
  - zlib=1.2.11=h7b6447c_3
prefix: /MMCI/TM/scratch/jebler/miniconda3/envs/pggtyper

