name: pangenie
channels:
  - bioconda
  - main
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - binutils_impl_linux-64=2.36.1=h193b22a_2
  - binutils_linux-64=2.36=hf3e587d_1
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.17.1=h27cfd23_0
  - ca-certificates=2022.12.7=ha878542_0
  - cereal=1.3.2=hd8ed1ab_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cmake=3.19.6=h973ab73_0
  - expat=2.4.1=h2531618_2
  - gcc=11.2.0=h702ea55_1
  - gcc_impl_linux-64=11.2.0=h82a94d6_11
  - gcc_linux-64=11.2.0=h39a9532_1
  - gxx_impl_linux-64=11.2.0=h82a94d6_11
  - gxx_linux-64=11.2.0=hacbe6df_1
  - jellyfish=2.2.10=h6bb024c_1
  - jemalloc=4.5.0=0
  - jsoncpp=1.9.5=h4bd325d_0
  - kernel-headers_linux-64=2.6.32=he073ed8_15
  - krb5=1.19.2=hac12032_0
  - ld_impl_linux-64=2.36.1=hea4e1c9_2
  - libcurl=7.78.0=h0b77cf5_0
  - libedit=3.1.20210910=h7f8727e_0
  - libev=4.33=h7f8727e_1
  - libffi=3.3=he6710b0_2
  - libgcc=7.2.0=h69d50b8_2
  - libgcc-devel_linux-64=11.2.0=h0952999_11
  - libgcc-ng=11.2.0=h1d223b6_11
  - libgomp=11.2.0=h1d223b6_11
  - libnghttp2=1.41.0=hf8bcb03_2
  - libsanitizer=11.2.0=he4da1e4_11
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-devel_linux-64=11.2.0=h0952999_11
  - libstdcxx-ng=11.2.0=he4da1e4_11
  - libuv=1.40.0=h7b6447c_0
  - lz4-c=1.9.3=h295c915_1
  - ncurses=6.3=h7f8727e_2
  - openssl=1.1.1l=h7f98852_0
  - pip=21.2.4=py39h06a4308_0
  - pkg-config=0.29.2=h1bed415_8
  - pkgconfig=1.5.4=py39h06a4308_0
  - python=3.9.7=h12debd9_1
  - python_abi=3.9=2_cp39
  - readline=8.1=h27cfd23_0
  - rhash=1.4.1=h3c74f83_1
  - setuptools=58.0.4=py39h06a4308_0
  - sqlite=3.36.0=hc218d9a_0
  - sysroot_linux-64=2.12=he073ed8_15
  - tk=8.6.11=h1ccaba5_0
  - tzdata=2021e=hda174b7_0
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
